//! Render episodes as copyable links or download scripts (parity with the original's script screen, plus M3U/JSON).
use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::str::FromStr;
use std::sync::LazyLock;

use regex::{NoExpand, Regex};
use serde::{Deserialize, Serialize};

use crate::error::CoreError;
use crate::model::Episode;

/// `"$OUT"`, `${OUT}` or bare `$OUT` in a custom command; bare `$OUT` only when the next character is
/// not `[A-Za-z0-9_]`, so `$OUTPUT` is left alone.
static OUT_TOKEN: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r#""\$OUT"|\$\{OUT\}|\$OUT(?-u:\b)"#).expect("valid regex"));

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
#[serde(tag = "kind", content = "command", rename_all = "snake_case")]
pub enum Format {
    Links,
    Wget,
    Aria2c,
    /// Arbitrary program: `<command> "<url>"` per line; `$OUT` in the command is replaced by the quoted file name.
    Custom(String),
    M3u,
    Json,
}

impl FromStr for Format {
    type Err = CoreError;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.trim().to_ascii_lowercase().as_str() {
            "links" => Ok(Format::Links),
            "wget" => Ok(Format::Wget),
            "aria2c" | "aria2" => Ok(Format::Aria2c),
            "custom" => Ok(Format::Custom(String::new())),
            "m3u" | "m3u8" => Ok(Format::M3u),
            "json" => Ok(Format::Json),
            other => Err(CoreError::Config(format!(
                "unknown export format `{other}` (links|wget|aria2c|custom|m3u|json)"
            ))),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
pub struct ExportItem {
    pub episode: Episode,
    /// Relative target path rendered from the naming template.
    pub file_name: String,
}

#[derive(Serialize)]
struct JsonItem<'a> {
    ordinal: u32,
    number: Option<u32>,
    title: &'a str,
    quality: Option<&'a str>,
    translator: Option<&'a str>,
    media_url: &'a str,
    subtitles: &'a [crate::model::Subtitle],
    file_name: &'a str,
}

/// Double-quote for POSIX sh: escapes `"`, `$`, `` ` `` and `\`.
fn sh_quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        if matches!(ch, '"' | '$' | '`' | '\\') {
            out.push('\\');
        }
        out.push(ch);
    }
    out.push('"');
    out
}

fn dirs_of(items: &[ExportItem]) -> BTreeSet<String> {
    items
        .iter()
        .filter_map(|i| i.file_name.rsplit_once('/').map(|(d, _)| d.to_string()))
        .collect()
}

pub fn render_export(items: &[ExportItem], format: &Format) -> String {
    let mut out = String::new();
    match format {
        Format::Links => {
            for i in items {
                let _ = writeln!(out, "{}", i.episode.media_url);
            }
        }
        Format::Wget => {
            out.push_str("#!/usr/bin/env sh\n# Generated by Seasonvar Downloader\nset -e\n");
            for d in dirs_of(items) {
                let _ = writeln!(out, "mkdir -p {}", sh_quote(&d));
            }
            for i in items {
                let _ = writeln!(
                    out,
                    "wget -c -O {} {}",
                    sh_quote(&i.file_name),
                    sh_quote(i.episode.media_url.as_str())
                );
            }
        }
        Format::Aria2c => {
            out.push_str("# aria2c input file — run: aria2c -c -x 4 -s 4 -i this_file.txt\n");
            for i in items {
                let (dir, name) = i
                    .file_name
                    .rsplit_once('/')
                    .map(|(d, n)| (Some(d), n))
                    .unwrap_or((None, i.file_name.as_str()));
                let _ = writeln!(out, "{}", i.episode.media_url);
                if let Some(d) = dir {
                    let _ = writeln!(out, "  dir={d}");
                }
                let _ = writeln!(out, "  out={name}");
            }
        }
        Format::Custom(cmd) => {
            let cmd = if cmd.trim().is_empty() {
                "echo"
            } else {
                cmd.trim()
            };
            for i in items {
                // `$OUT` (bare, `${OUT}` or already double-quoted) becomes the safely quoted file name
                // in a single pass, so a `$OUT` inside the file name itself is never re-substituted.
                let name = sh_quote(&i.file_name);
                let with_out = OUT_TOKEN.replace_all(cmd, NoExpand(name.as_str()));
                let _ = writeln!(out, "{with_out} {}", sh_quote(i.episode.media_url.as_str()));
            }
        }
        Format::M3u => {
            out.push_str("#EXTM3U\n");
            for i in items {
                let _ = writeln!(
                    out,
                    "#EXTINF:-1,{}\n{}",
                    i.episode.title, i.episode.media_url
                );
            }
        }
        Format::Json => {
            let rows: Vec<JsonItem> = items
                .iter()
                .map(|i| JsonItem {
                    ordinal: i.episode.ordinal,
                    number: i.episode.number,
                    title: &i.episode.title,
                    quality: i.episode.quality.as_deref(),
                    translator: i.episode.translator.as_deref(),
                    media_url: i.episode.media_url.as_str(),
                    subtitles: &i.episode.subtitles,
                    file_name: &i.file_name,
                })
                .collect();
            out = serde_json::to_string_pretty(&rows).expect("serializable");
            out.push('\n');
        }
    }
    out
}
