//! Tauri layer: commands + events over `seasonvar_core`, typed bindings via tauri-specta.
use serde::{Deserialize, Serialize};
use specta_typescript::Typescript;
use tauri::Manager;
use tauri_specta::{Builder, Event, collect_commands, collect_events};

/// Application version (from this crate's Cargo.toml).
#[tauri::command]
#[specta::specta]
fn app_version() -> String {
    env!("CARGO_PKG_VERSION").to_string()
}

/// Emitted when the main webview has finished loading the page.
#[derive(Debug, Clone, Serialize, Deserialize, specta::Type, Event)]
pub struct AppReady {
    pub version: String,
}

pub fn run() {
    let builder = Builder::<tauri::Wry>::new()
        .commands(collect_commands![app_version])
        .events(collect_events![AppReady]);

    #[cfg(debug_assertions)]
    builder
        .export(
            Typescript::default()
                .header("// @ts-nocheck\n// Generated by tauri-specta — do not edit.\n"),
            concat!(env!("CARGO_MANIFEST_DIR"), "/../src/bindings.ts"),
        )
        .expect("failed to export TypeScript bindings");

    tauri::Builder::default()
        .plugin(tauri_plugin_single_instance::init(|app, _argv, _cwd| {
            if let Some(window) = app.get_webview_window("main") {
                let _ = window.set_focus();
            }
        }))
        .plugin(tauri_plugin_window_state::Builder::new().build())
        .plugin(tauri_plugin_log::Builder::new().build())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_store::Builder::new().build())
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_clipboard_manager::init())
        .invoke_handler(builder.invoke_handler())
        .on_page_load(|webview, payload| {
            if payload.event() == tauri::webview::PageLoadEvent::Finished {
                let _ = AppReady {
                    version: env!("CARGO_PKG_VERSION").to_string(),
                }
                .emit(webview);
            }
        })
        .setup(move |app| {
            builder.mount_events(app);
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running Seasonvar Downloader");
}
